name = "fundcal"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "FUND_DATA"
id = "e38469490c3146f987cab362c2603d02"
preview_id = "d63cdb5fc401443b9815c7aa15961e65"
